export const BOOK_ADD = 'BOOK_ADD';
export const BOOK_DELETE = 'BOOK_DELETE';
export const BOOK_GENRE = 'BOOK_GENRE';
export const BOOK_EDIT = 'BOOK_EDIT';


export const BOOK_ADD_TO_WISHLIST = 'BOOK_ADD_TO_WISHLIST';
export const BOOK_DELETE_FROM_WISHLIST = 'BOOK_DELETE_FROM_WISHLIST';

